name: Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Adding executable permissions to generatedocs script
      run: |
        chmod +x ./scripts/generatedocs.py

    - name: Converting IPython Notebooks to Markdowns
      run: |
        ./scripts/generatedocs.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: |
          [Automated change] Regenerate documents from updated IPython Notebooks

          Regenerate documents from updated IPython Notebooks using "generatedoc.py"
          script.
          
          Any file that wouldn't be inside of the "_BASE_AI_DIR" directory would be
          omitted so, to reflect your changes in the documents change IPython
          Notebooks inside of the "_BASE_AI_DIR" directory. 

          Signed-off-by: github-actions[bot]

        branch: master
